version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_bin
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "bh"
      MYSQL_USER: "roots"
      MYSQL_PASSWORD: "roots"
    networks:
      - base
#    network_mode: "host"
    ports:
      - "3306:3306"
    volumes:
#      - /home/vth/data/:/var/lib/mysql/
      - mariadb-data:/var/lib/mysql/

  django-web:
    image: sevolloves/test1
    restart: always
#    build:
#      context: .
#      dockerfile: Dockerfile
    networks:
      - base
#    network_mode: "host"
    ports:
      - "8000:8000"
networks:
  base:

volumes:
  mariadb-data:
